Added Feature: choose shown streetnames from zoomlevel abstraction.
HPI-SWA-Teaching/OpenSqueakMap pull request #44
Opened 2017-06-15 09:42 UTC by JoshCoder42

2017-06-15 10:49 UTC, bakoe requested changes
Please remove the two Transcript calls, especially from `selectStreetsToShow` -- makes the method much more readable and increases overall performance (Transcript calls are quit slow).

2017-06-15 11:04 UTC, bakoe approved these changes

2017-06-22 11:20 UTC, birneamstiel approved these changes

2017-06-22 11:20 UTC, birneamstiel commented on packages/OpenSqueakMap.package/OSMRenderObject.class/instance/showStreetName..st
> +	Transcript show: aSet.
please remove transcript outputs :-)

2017-06-22 11:20 UTC, birneamstiel commented on packages/OpenSqueakMap.package/OSMChunk.class/instance/selectStreetsToShow..st
> +	self zoomlevelAbstraction at: self viewport zoomLevel ifPresent: [:aSet | Transcript show: aSet. aMorph showStreetName: aSet].
one more transcript show:...

2017-06-26 10:33 UTC, birneamstiel commented
@JoshCoder42: Nach dem mergen des `dev`-Branches funktioniert das nicht mehr so richtig... Schaust du dir das nochmal an?

2017-06-27 14:22 UTC, merged